// <auto-generated />
using System;
using KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Migrations
{
    [DbContext(typeof(HR_STRIVE_DbContext))]
    partial class HR_STRIVE_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryRegion")
                        .HasColumnType("int");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HolidayDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeSheetId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AddressId");

                    b.HasIndex("HolidayDetailsId");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.HolidayDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarryOver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entitled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HolidayRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Remaining")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HolidayRequestId");

                    b.ToTable("HolidayDetails");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.HolidayRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmOrPm")
                        .HasColumnType("int");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HolidayRequest");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Metricz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Metricz");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Employee", b =>
                {
                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.HolidayDetails", "HolidayDetails")
                        .WithMany()
                        .HasForeignKey("HolidayDetailsId");

                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.TimeSheet", "TimeSheet")
                        .WithMany()
                        .HasForeignKey("TimeSheetId");

                    b.Navigation("Address");

                    b.Navigation("HolidayDetails");

                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.HolidayDetails", b =>
                {
                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.HolidayRequest", "HolidayRequest")
                        .WithMany()
                        .HasForeignKey("HolidayRequestId");

                    b.Navigation("HolidayRequest");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Metricz", b =>
                {
                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Employee", null)
                        .WithMany("UserPerformanceReviews")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.UserAccount", b =>
                {
                    b.HasOne("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KAIS.HR_DYNAMIC.HR_STRIVE.REPOSITORY.Model.Employee", b =>
                {
                    b.Navigation("UserPerformanceReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
